# Name of this workflow
name: Go Lint & Test

# Triggered on pull request and push events for any branch
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

# Defining jobs
jobs:
  # Lint job for Go code
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          check-latest: true
      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.3.3
      - name: Run Staticcheck
        run: staticcheck ./...

  # Test job for Go on Linux with Go 1.22
  test:
    name: Test Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          check-latest: true
      - name: Run Tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
          fail_ci_if_error: true

  # Benchmark job
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          check-latest: true
      - name: Run Benchmarks
        run: go test -bench=. -benchmem ./...
