# Name of this workflow
name: Go Lint & Test

# Triggered on pull request and push events for any branch
on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main"]

# Defining jobs
jobs:
  # Lint job for Go code
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: true
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=5m --go=1.22
          go-version-file: go.mod

  # Test job for Go on Linux with Go 1.22
  test:
    name: Test on Linux with Go 1.22
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: true
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Test
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
          go tool cover -func=coverage.txt

  # Benchmark job
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: true
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Run Benchmarks
        run: |
          go test -bench=. -benchmem ./...
